// export default WeatherForecast {
//     "timezone": "Europe/Moscow",
//     "ob_time": "2019-06-16 20:30",
//     "country_code": "RU",
//     "state_code": "66",
//     "city_name": "Saint Petersburg",
//     "wind_spd": 1,
//     "last_ob_time": "2019-06-16T20:30:00",
//     "wind_cdir_full": "north",
//     "wind_cdir": "N",
//     "slp": 1013,
//     "vis": 5,
//     "h_angle": -90,
//     "sunset": "19:23",
//     "dni": 0,
//     "dewpt": 12,
//     "snow": 0,
//     "uv": 0,
//     "precip": 0,
//     "wind_dir": 0,
//     "sunrise": "00:36",
//     "ghi": 0,
//     "dhi": 0,
//     "aqi": 44,
//     "lat": 59.93863,
//     "weather": {
//       "icon": "c02n",
//       "code": "802",
//       "description": "Scattered clouds"
//     },
//     "datetime": "2019-06-16:20",
//     "temp": 15,
// }